#remote_theme: ozgrozer/dasper
#remote_theme: niklasbuschmann/contrast
remote_theme: rohanchandra/type-theme

plugins:
  - jekyll-remote-theme

# SITE CONFIGURATION
baseurl: ""
url: "https://fabiand.github.io"
